import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import FeedbackModal from "@/components/modals/FeedbackModal";
import Prompt from "@/components/Prompt";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark:bg-[#1E1E1F] dark:text-white gradient-background text-black`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen">
            <Sidebar />

            <div className=" md:w-[calc(100%_-_288px)] md:ml-auto">
              <Navbar />
              <main className="h-[calc(100%_-_64px)]  mt-16 p-4">
                {children}
                </main>
            </div>
          </div>
          <FeedbackModal />
        </ThemeProvider>
      </body>
    </html>
  );
}
